version: "3.6"

services:
    postgres:
        image: postgres:9.6
        restart: unless-stopped
        environment:
            - POSTGRES_USER=latency
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - psql-db-data:/var/lib/postgresql/data

#  postgres-test:
#    image: postgres:9.6
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=latency
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "54320:5432"
#    volumes:
#      - psql-db-data-test:/var/lib/postgresql/data

volumes:
    psql-db-data:
    psql-db-data-test:
