version: "3.6"

services:
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        environment:
            - POSTGRES_USER=latency
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - psql-db-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_tests
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: user@user.com
            PGADMIN_DEFAULT_PASSWORD: user
        volumes:
            - pgadmin:/var/lib/pgadmin    

volumes:
    psql-db-data:
    pgadmin: