### PUT /user/:id
PUT http://localhost:3000/user/c7c9fb69-8135-4fe4-b20d-eea8f8f6ee59
Content-Type: application/json

{
"name": "AARON 59",
"roleId": "2b2fe2d7-252f-48c6-80c5-e80799f63f44"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


### GET /user
GET http://localhost:3000/user
Accept: application/json
