### GET /user
GET http://localhost:3000/user


> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data === 'user service', "Response is not correct");
});
%}

### GET /dashboard
GET http://localhost:3000/dashboard

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data === 'dashboard service', "Response is not correct");
});
%}

### GET /auth
GET http://localhost:3000/auth

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data === 'user service', "Response is not correct");
});
%}

### POST /auth
POST http://localhost:3000/auth

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}
