### GET /deal
GET http://localhost:3000/deal
Accept: application/json

### GET /deal/:id
GET http://localhost:3000/deal/c7c9fb69-8135-4fe4-b20d-eea8f8f6ee52
Content-Type: application/json

### PUT /deal/:id
PUT http://localhost:3000/deal/c7c9fb69-8135-4fe4-b20d-eea8f8f6ee52
Content-Type: application/json

{
	"name": "ASCENSO",
	"alias": "DESCENSO",
	"fee": 30000
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}
